name: advanced-security/python-lint-code-scanning-action@v1

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Comprobar seguridad del codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
    
